### ISSUE TITLE
Use kebab-case for inputs and outputs?

### ISSUE THREAD

**Issue by nirvdrum** [chrnorm/deployment-action#22]
All of the documentation for GitHub Actions uses the [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles) naming convention. This project, however, uses snake-case. As such, it's the only part of our entire CD config that uses snake-case and it can throw people off.

I wouldn't want to break anything on anyone, so if supporting both isn't a problem, that'd be helpful. I can do up a PR for it, but don't want to spend the time if there's no support for the change.

**Comment by chrnorm** [comment]
Good point @nirvdrum - I'm about to release v2 of this action which has some other breaking changes so I will take the opportunity to standardise on kebab-case here!
