### ISSUE TITLE
Validation failures when using in_progress state

### ISSUE THREAD

**Issue by sjparkinson** [chrnorm/deployment-action#3]
https://github.com/chrnorm/deployment-action/blob/fad9de7d8b901b20426466e4ed01acf55b5b2469/src/main.ts#L8

In this action and in https://github.com/chrnorm/deployment-status I believe you need to include the following media types:

```
application/vnd.github.flash-preview+json
application/vnd.github.ant-man-preview+json
```

Here's an example failure https://github.com/sjparkinson/isitup.org/commit/8f493dc202948137370dddc9c002733194d985d9/checks.

```
##[error]HttpError: Validation Failed
##[error]Validation Failed
##[error]Node run failed with exit code 1
```

**Comment by chrnorm** [comment]
Hi @sjparkinson, thanks for the issue. I've attempted to add the `ant-man` and `flash` previews to the initialisation of the GitHub client to fix this issue based on reading the [Octokit docs here](https://octokit.github.io/rest.js/#previews).

```js
const client = new github.GitHub(token, { previews: ["flash", "ant-man"] });
```

I've just released a new version which includes this - chrnorm/deployment-action@v1.1.1. Please try that and let me know if that works.
