### ISSUE TITLE
Feature: Support `task` attribute

### ISSUE THREAD

**Issue by callum-tait-pbx** [chrnorm/deployment-action#36]
https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#deployment

It would be great to support all the possible properties, I am intending on using this action but also need the task property

**Comment by chrnorm** [comment]
Thanks for the issue! I've added support for this in #53 which will be released as v2 of this action. Sorry for the late reply here, I haven't been using GitHub deployments in any of my projects for the last couple of years so haven't been keeping this repo up to date.
