### ISSUE TITLE
[Error: Not Found] Provide better error messaging

### ISSUE THREAD

**Issue by iautom8things** [chrnorm/deployment-action#45]
This is all that is shown if the configured user's github token does not have permissions to create deployments on the repository:

```bash
> Run chrnorm/deployment-action@v1.2.0
Error: HttpError: Not Found
Error: Not Found
```

It'd be a lot more helpful if the messaging indicated that this HTTP error was specifically related to the call to the github api (and not that the `target_url` is attempted to be queried for some reason, which was my first hunch since I had provided an internal server).

```
Error: Unable to create deployment. Either the repository does not exist or the provided token does not have the proper permissions to do so.
```

**Comment by chrnorm** [comment]
Thanks for the issue @iautom8things. I'm unsure of the best approach to parse the caught error but I've made an improvement in #58 so it should be at least clearer the error relates to calling the GitHub API rather than trying to call `target_url`.
