### ISSUE TITLE
Misleading info about target_url, typos in doc + support for environment_url

### ISSUE THREAD

**Issue by JanMikes** [chrnorm/deployment-action#6]
Hi there!

In docs, you write:
> target_url | (Optional) The target URL. This should be the URL of the app once deployed

But it is actually not true [(source)](https://developer.github.com/v3/repos/deployments/#parameters-2):
> The target URL to associate with this status. This URL should contain output to keep the user updated while the task is running or serve as historical information for what happened in the deployment. Default: "" Note: It's recommended to use the log_url parameter, which replaces target_url.

As well it is deprecated and should use log_url instead.

Another thing, in your examples you use input `target-url` with dash, instead of underscore.

Do you plan adding `environment_url` input support?

Thank you

**Comment by chrnorm** [comment]
Hi @JanMikes, thanks for bringing this to my attention!

I think I misread the GitHub documentation while creating the first version and assumed that `target_url` was the URL of the application. I will update the action and push a new version to fix this. My proposed fix is to swap `target_url` to `environment_url` in the `client.repos.createDeploymentStatus()` method.

At this stage I won't rename the `target_url` input to the action to avoid breaking the action for anyone who is using it. I'll make a PR now.

Also, the readme has been updated in #10 to fix the target URL typo.
