### ISSUE TITLE
Is this action still relevant?

### ISSUE THREAD

**Issue by nicwortel** [chrnorm/deployment-action#68]
First of all, thank you for publishing this action. I have been using it for 1.5 years to track deployments by GitHub Actions and it works very well.

However, today I found out that GitHub Actions now has [its own feature to manage deployments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment). By adding `environment: production` to a job, GitHub Actions will create a deployment (and an environment, if it doesn't exist yet) and update its status based on the result of the job.

The URL for the deployment can also be specified, which is then also shown in the visualization graph for the workflow run:

![Deploy graph](https://docs.github.com/assets/cb-23185/images/help/images/deploy-graph.png)

And the deployment history will now show the user who triggered the deployment instead of **github-actions**:

![afbeelding](https://user-images.githubusercontent.com/1055691/183080041-e15e1681-762c-4202-9b33-8dc8dd2379d3.png)

So I am opening this issue to discuss the question whether or not this action is still relevant. Is all the provided functionality now covered by GitHub Actions itself? Or are there still reasons / scenarios for which this action is offering functionality not covered by GitHub Actions?

**Comment by liamoneill** [comment]
Hey @nicwortel, we are using this action (forked with #69) to create deployments on a different repository than the repository that's running the workflow.

Doesn't appear like GHA's `environment` block supports creating deployments outside the workflow's repository. May be a rather obscure use case but thought I'd mention it.

**Comment by karfau** [comment]
Another issue is that the "environment approach" currently doesn't support any parameters other then name and url: You can not pass the ref that is being deployed or any payload.

https://github.com/orgs/community/discussions/19304

**Comment by sgammon** [comment]
you also cannot create a deploy as a step, only a job, which is inconvenient for many use cases. i do not see a way to set the transient or production environment flags on the main "environment approach," either.

**Comment by karfau** [comment]
This alternative seems to provide a much better DevX:
https://github.com/marketplace/actions/github-deployments

**Comment by sgammon** [comment]
seems relevant to me ¯\_(ツ)_/¯

**Comment by piotrekkr** [comment]
I also use prefer using action over standard deploy handling in GitHub. I need to create/update deployments with some custom payload. This payload contains commits that are inside release. Deploy event with this payload is then sent using GitHub webhooks to some endpoint that collects them and then calculate some DORA metrics. This is not possible using normal GitHub deployment flow. @karfau Thanks for this link. Will use this actions since this one seems abandoned.

**Comment by nicwortel** [comment]
Sounds like there are still multiple use cases where this action provides a benefit over GitHub's Environments! I'm closing the issue.
