### ISSUE TITLE
Figured out how to trigger `deployment` action from inside the workflow

### ISSUE THREAD

**Issue by rclayton-the-terrible** [chrnorm/deployment-action#7]
> Heads up! Currently, there is a GitHub Actions limitation where events fired inside an action will not trigger further workflows. If you use this action in your workflow, it will not trigger any "Deployment" workflows.

I was able to work around this.  While not ideal, if you use a token that is not the Action's `GITHUB_TOKEN`, this will work.  I define a secret called `GITHUB_DEPLOY_TOKEN` and use that for API calls.

**Comment by chrnorm** [comment]
@rclayton-the-terrible thanks for the heads up on this - I will add it to the README so that other users will be aware!

**Comment by yurist38** [comment]
Guys, do you know what permissions exactly the token need to have in order to make it?

**Comment by sethidden** [comment]
GitHub docs reference:
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

I'm currently setting this up, I'll keep you updated as to which scope is necessary
