### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by lesleyxyz** [chrnorm/deployment-action#73]
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
This action should be updated to Node.js 16 (atleast).

**Comment by piotrekkr** [comment]
I think it is already fixed

**Comment by lesleyxyz** [comment]
It indeed does say `using: node16` in `action.yml`
My bad. It's because I'm using `chrnorm/deployment-action@releases/v1` and `chrnorm/deployment-status@releases/v1` while there is a v2
